# Generated by Django 3.1.5 on 2021-02-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memex', '0003_auto_20210211_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memeinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
